### ISSUE TITLE
Various RNA functions are missing

### ISSUE THREAD

**Issue by ClairePA** [scilligence/JsHELM#23]
The editor must be able to do the following:
- Get complimentary strand
- Annotate as sense or antisense
- Display 3' or 5' label at the ends of the molecule - **NB** this must be chemically determined, not added by the user. It is not an annotation, just a visualisation of an aspect of the chemical structure.

**Comment by tony-yuan** [comment]
fixed in 8-30 update

**Comment by ClairePA** [comment]
Sense and antisense are present, but not 'get complimentary strand'. Please add this function. 

The About box on the context menu should state "About HELM Editor" not JS Draw. The reference to JSDrawLite in the popup box should be removed.

**Comment by tony-yuan** [comment]
About HELM Editor
-----------------
Built on <a href='some link'>JSDraw.Lite</a> (Free Version)

**Comment by ClairePA** [comment]
'Get complimentary strand' has been added and the About box changed, however the right slick menu item should say 'About the HELM Editor' not 'About JSDraw'.

**Comment by tony-yuan** [comment]
Fixed in 2.0.0.2016-09-27

**Comment by tony-yuan** [comment]
About... fixed in 2016-10-04 udpate

**Comment by ClairePA** [comment]
About box should include:
•	The brackets should include the words "open source" not "free version". 
•	The link still takes you to a page which is largely about the paid version of JSDraw, we need it to go to something which is exclusively about open-source JSDraw or it could not go to anything at all. It is very important to our commercial HELM adopters to know that HELM is fully open source. 

![image](https://cloud.githubusercontent.com/assets/3986896/19654697/5b5a435a-9a11-11e6-85ec-dc386ffa8e17.png)

The tab that is displayed in your browser also includes talks about JSDraw rather than HELM editor. 
 
![image](https://cloud.githubusercontent.com/assets/3986896/19654718/71f2222c-9a11-11e6-8b79-a4ce18bfec64.png)


Please can you change this for all three modules – the editor, monomer manager and ruleset manager. 

The "about" box in the monomer editor could return to being ‘About JSDraw’ if you want since this is the small molecule editor and therefore should represent the chemical editor itself. The about box here could be about JSDraw entirely and not mention HELM at all. A link here could take you to the information about full JSDraw.

**Comment by ClairePA** [comment]
Confirmed fixed.
