### ISSUE TITLE
Hover over should be inhibited when right-click menu is displayed

### ISSUE THREAD

**Issue by ClairePA** [scilligence/JsHELM#67]
![image](https://cloud.githubusercontent.com/assets/3986896/19807099/6b62320a-9d16-11e6-84a4-5c1a2f3e5314.png)
When I right-click on a monomer to get the pop-up menu I often get the monomer displayed as well which makes it impossible to see or select the menu options.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-31 update

**Comment by ClairePA** [comment]
Steps to reproduce.

- Have either a monomer selected or the 'select' tool highlighted.
- right-click on a monomer
- I get the context menu displayed, but then the monomer pop-up as well.

If I move my mouse even a little I the pop-up will go away and if I right-click on a different monomer the pop-up does not appear. It is only an issue for the first right-click on a monomer.

**Comment by ClairePA** [comment]
Does not happen when I use Chrome - only Edge.

**Comment by scilligence** [comment]
Fixed in 2016-12-15 update

**Comment by ClairePA** [comment]
Confirmed fixed - much better.
