### ISSUE TITLE
Search for monomers should be possible using the name field

### ISSUE THREAD

**Issue by ypotier** [scilligence/JsHELM#71]

**Comment by tony-yuan** [comment]
Fixed in 2016-11-13 update

**Comment by ClairePA** [comment]
Tested - looks fixed. Yohann, please can you check?

**Comment by ClairePA** [comment]
Hi Yohann, could you check this one please?

**Comment by ypotier** [comment]
It is using the name field and I see it is working with the * symbol if I want to search with wildcards: great, thank you!
