### ISSUE TITLE
Monomers JSDraw toolbar page to edit

### ISSUE THREAD

**Issue by ypotier** [scilligence/JsHELM#79]
The Monomer Library page has a different toolbar in JSDraw than the Main canvas, there are options we do not need:
- N2S does not seems to work (with common name or SMILES)
- Text
- Reaction
- Peptide 
I suggest to remove them

**Comment by tony-yuan** [comment]
Fixed in 2016-11-04 update

**Comment by ClairePA** [comment]
Appears fixed - Yohann please could you confirm?

**Comment by ypotier** [comment]
confirmed fixed
